name: Inject Config
description: "Inject variables into XCConfig"

inputs:
  api-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Inject variables into environment file
      env:
        API_KEY: ${{ inputs.api-key }}
      run: |
        cp TestEnv/TestEnv/Template.xcconfig TestEnv/TestEnv/Environment/Production.xcconfig
        sed -i "s|%%API_KEY%%|$API_KEY|g" TestEnv/TestEnv/Environment/Production.xcconfig
      shell: bash

    - name: Verify file contents
      run: cat TestEnv/TestEnv/Environment/Production.xcconfig
      shell: bash
