name: Inject Config
description: "Inject variables into XCConfig"

inputs:
  api-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug - List all files
      run: ls -R
      shell: bash

    - name: Ensure Environment directory exists
      run: mkdir -p TestEnv/TestEnv/Environment
      shell: bash

    - name: Inject variables into environment file
      env:
        API_KEY: ${{ inputs.api-key }}
      run: |
        cp TestEnv/TestEnv/Template.xcconfig TestEnv/TestEnv/Environment/Production.xcconfig
        sed -i '' "s|%%API_KEY%%|$API_KEY|" TestEnv/TestEnv/Environment/Production.xcconfig
      shell: bash

    - name: Verify file existence
      run: ls -R TestEnv/TestEnv/
      shell: bash
