name: Inject Config
description: "Inject variables into XCConfig"

inputs:
  api-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Ensure Environment directory exists
      run: mkdir -p TestEnv/TestEnv/Environment
      shell: bash

    - name: Inject variables into environment file
      working-directory: TestEnv/TestEnv
      env:
        API_KEY: ${{ inputs.api-key }}
      run: |
        cp Template.xcconfig Environment/Production.xcconfig
        sed -i '' "s|%%API_KEY%%|$API_KEY|" Environment/Production.xcconfig
      shell: bash

    - name: Verify file existence
      run: ls -R TestEnv/TestEnv/
      shell: bash
