name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true  
      choice:
        type: choice
        description: 'Environment to deploy to (staging, production)'
        required: true
        options:
          - 'Staging'
          - 'Production'

jobs:
  uploadToTestFlight:
    name: TestFlight Deployment
    environment: ${{ inputs.choice }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Pre Build steps
        uses: ./.github/actions/inject-config
        with:
            api-key: ${{ secrets.API_KEY }}
          
      - name: Print API Key (Base64 Encoded)
        run: echo "$API_KEY" | base64
        env:
            API_KEY: ${{ secrets.API_KEY }}
